#Student Number 09892205
#Student Name Javio Felix

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1064, 687)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Main_Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Main_Tab.setGeometry(QtCore.QRect(20, 10, 981, 641))
        self.Main_Tab.setObjectName("Main_Tab")
        self.Initialize_Tab = QtWidgets.QWidget()
        self.Initialize_Tab.setObjectName("Initialize_Tab")
        self.pushButton_3 = QtWidgets.QPushButton(self.Initialize_Tab)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 220, 291, 101))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.Main_Tab.addTab(self.Initialize_Tab, "")
        self.customer = QtWidgets.QWidget()
        self.customer.setObjectName("customer")
        self.Customer_Tab = QtWidgets.QTabWidget(self.customer)
        self.Customer_Tab.setGeometry(QtCore.QRect(30, 60, 921, 551))
        self.Customer_Tab.setObjectName("Customer_Tab")
        self.create_cus_tab = QtWidgets.QWidget()
        self.create_cus_tab.setObjectName("create_cus_tab")
        self.verticalGroupBox = QtWidgets.QGroupBox(self.create_cus_tab)
        self.verticalGroupBox.setGeometry(QtCore.QRect(160, 0, 160, 411))
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_CreateCustomer_CustomerID = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit_CreateCustomer_CustomerID.setText("")
        self.lineEdit_CreateCustomer_CustomerID.setObjectName("lineEdit_CreateCustomer_CustomerID")
        self.verticalLayout.addWidget(self.lineEdit_CreateCustomer_CustomerID)
        self.lineEdit_CreateCustomer_FirstName = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit_CreateCustomer_FirstName.setObjectName("lineEdit_CreateCustomer_FirstName")
        self.verticalLayout.addWidget(self.lineEdit_CreateCustomer_FirstName)
        self.lineEdit_CreateCustomer_LastName = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit_CreateCustomer_LastName.setObjectName("lineEdit_CreateCustomer_LastName")
        self.verticalLayout.addWidget(self.lineEdit_CreateCustomer_LastName)
        self.lineEdit_CreateCustomer_Address = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit_CreateCustomer_Address.setText("")
        self.lineEdit_CreateCustomer_Address.setObjectName("lineEdit_CreateCustomer_Address")
        self.verticalLayout.addWidget(self.lineEdit_CreateCustomer_Address)
        self.lineEdit_CreateCustomer_Email = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit_CreateCustomer_Email.setText("")
        self.lineEdit_CreateCustomer_Email.setObjectName("lineEdit_CreateCustomer_Email")
        self.verticalLayout.addWidget(self.lineEdit_CreateCustomer_Email)
        self.lineEdit_CreateCustomer_Phone = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit_CreateCustomer_Phone.setText("")
        self.lineEdit_CreateCustomer_Phone.setObjectName("lineEdit_CreateCustomer_Phone")
        self.verticalLayout.addWidget(self.lineEdit_CreateCustomer_Phone)
        self.lineEdit_CreateCustomer_CreditCard = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit_CreateCustomer_CreditCard.setText("")
        self.lineEdit_CreateCustomer_CreditCard.setObjectName("lineEdit_CreateCustomer_CreditCard")
        self.verticalLayout.addWidget(self.lineEdit_CreateCustomer_CreditCard)
        self.verticalGroupBox_2 = QtWidgets.QGroupBox(self.create_cus_tab)
        self.verticalGroupBox_2.setGeometry(QtCore.QRect(0, 0, 160, 411))
        self.verticalGroupBox_2.setObjectName("verticalGroupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalGroupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_CustomerID = QtWidgets.QLabel(self.verticalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_CustomerID.setFont(font)
        self.label_CustomerID.setObjectName("label_CustomerID")
        self.verticalLayout_2.addWidget(self.label_CustomerID)
        self.label_FirstName = QtWidgets.QLabel(self.verticalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_FirstName.setFont(font)
        self.label_FirstName.setObjectName("label_FirstName")
        self.verticalLayout_2.addWidget(self.label_FirstName)
        self.label_LastName = QtWidgets.QLabel(self.verticalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_LastName.setFont(font)
        self.label_LastName.setObjectName("label_LastName")
        self.verticalLayout_2.addWidget(self.label_LastName)
        self.label_Address = QtWidgets.QLabel(self.verticalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Address.setFont(font)
        self.label_Address.setObjectName("label_Address")
        self.verticalLayout_2.addWidget(self.label_Address)
        self.label_Email = QtWidgets.QLabel(self.verticalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Email.setFont(font)
        self.label_Email.setObjectName("label_Email")
        self.verticalLayout_2.addWidget(self.label_Email)
        self.label_Phone = QtWidgets.QLabel(self.verticalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_Phone.setFont(font)
        self.label_Phone.setObjectName("label_Phone")
        self.verticalLayout_2.addWidget(self.label_Phone)
        self.label_CreditCard = QtWidgets.QLabel(self.verticalGroupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_CreditCard.setFont(font)
        self.label_CreditCard.setObjectName("label_CreditCard")
        self.verticalLayout_2.addWidget(self.label_CreditCard)
        self.pushButton_CreateCustomer_Confirm = QtWidgets.QPushButton(self.create_cus_tab)
        self.pushButton_CreateCustomer_Confirm.setGeometry(QtCore.QRect(430, 160, 171, 81))
        self.pushButton_CreateCustomer_Confirm.setObjectName("pushButton_CreateCustomer_Confirm")
        self.label_3 = QtWidgets.QLabel(self.create_cus_tab)
        self.label_3.setGeometry(QtCore.QRect(360, 90, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Customer_Tab.addTab(self.create_cus_tab, "")
        self.view_cus_tab = QtWidgets.QWidget()
        self.view_cus_tab.setObjectName("view_cus_tab")
        self.tableWidget_CustomerDetail = QtWidgets.QTableWidget(self.view_cus_tab)
        self.tableWidget_CustomerDetail.setGeometry(QtCore.QRect(10, 50, 871, 241))
        self.tableWidget_CustomerDetail.setObjectName("tableWidget_CustomerDetail")
        self.tableWidget_CustomerDetail.setColumnCount(7)
        self.tableWidget_CustomerDetail.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_CustomerDetail.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_CustomerDetail.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_CustomerDetail.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_CustomerDetail.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_CustomerDetail.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_CustomerDetail.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_CustomerDetail.setHorizontalHeaderItem(6, item)
        self.pushButton_CustomerDetail_View = QtWidgets.QPushButton(self.view_cus_tab)
        self.pushButton_CustomerDetail_View.setGeometry(QtCore.QRect(270, 330, 171, 81))
        self.pushButton_CustomerDetail_View.setObjectName("pushButton_CustomerDetail_View")
        self.Customer_Tab.addTab(self.view_cus_tab, "")
        self.update_cus_tab = QtWidgets.QWidget()
        self.update_cus_tab.setObjectName("update_cus_tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.update_cus_tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 10, 634, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_UpdateText2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_UpdateText2.setFont(font)
        self.label_UpdateText2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_UpdateText2.setObjectName("label_UpdateText2")
        self.verticalLayout_9.addWidget(self.label_UpdateText2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_LastName_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_LastName_2.setFont(font)
        self.label_LastName_2.setObjectName("label_LastName_2")
        self.horizontalLayout_2.addWidget(self.label_LastName_2)
        self.lineEdit_UpdateCustomer_LastName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_UpdateCustomer_LastName.setText("")
        self.lineEdit_UpdateCustomer_LastName.setObjectName("lineEdit_UpdateCustomer_LastName")
        self.horizontalLayout_2.addWidget(self.lineEdit_UpdateCustomer_LastName)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.label_UpdateText1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_UpdateText1.setFont(font)
        self.label_UpdateText1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_UpdateText1.setObjectName("label_UpdateText1")
        self.verticalLayout_9.addWidget(self.label_UpdateText1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_FirstName_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_FirstName_2.setFont(font)
        self.label_FirstName_2.setObjectName("label_FirstName_2")
        self.horizontalLayout.addWidget(self.label_FirstName_2)
        self.lineEdit_UpdateCustomer_CustomerID = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_UpdateCustomer_CustomerID.setText("")
        self.lineEdit_UpdateCustomer_CustomerID.setObjectName("lineEdit_UpdateCustomer_CustomerID")
        self.horizontalLayout.addWidget(self.lineEdit_UpdateCustomer_CustomerID)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.pushButton_UpdateCustomer_Update = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_UpdateCustomer_Update.setObjectName("pushButton_UpdateCustomer_Update")
        self.verticalLayout_9.addWidget(self.pushButton_UpdateCustomer_Update)
        self.Customer_Tab.addTab(self.update_cus_tab, "")
        self.del_cus_tab = QtWidgets.QWidget()
        self.del_cus_tab.setObjectName("del_cus_tab")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.del_cus_tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(40, 100, 639, 80))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_DelereCustomer = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_DelereCustomer.setFont(font)
        self.label_DelereCustomer.setObjectName("label_DelereCustomer")
        self.horizontalLayout_3.addWidget(self.label_DelereCustomer)
        self.lineEdit_DelereCustomer = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_DelereCustomer.setText("")
        self.lineEdit_DelereCustomer.setObjectName("lineEdit_DelereCustomer")
        self.horizontalLayout_3.addWidget(self.lineEdit_DelereCustomer)
        self.pushButton_DelereCustomer_Delete = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_DelereCustomer_Delete.setObjectName("pushButton_DelereCustomer_Delete")
        self.horizontalLayout_3.addWidget(self.pushButton_DelereCustomer_Delete)
        self.label_DelereCustomer_2 = QtWidgets.QLabel(self.del_cus_tab)
        self.label_DelereCustomer_2.setGeometry(QtCore.QRect(40, 30, 621, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_DelereCustomer_2.setFont(font)
        self.label_DelereCustomer_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_DelereCustomer_2.setObjectName("label_DelereCustomer_2")
        self.Customer_Tab.addTab(self.del_cus_tab, "")
        self.Main_Tab.addTab(self.customer, "")
        self.order = QtWidgets.QWidget()
        self.order.setObjectName("order")
        self.Order_Tab = QtWidgets.QTabWidget(self.order)
        self.Order_Tab.setGeometry(QtCore.QRect(20, 10, 831, 541))
        self.Order_Tab.setObjectName("Order_Tab")
        self.place_order_tab = QtWidgets.QWidget()
        self.place_order_tab.setObjectName("place_order_tab")
        self.verticalGroupBox_3 = QtWidgets.QGroupBox(self.place_order_tab)
        self.verticalGroupBox_3.setGeometry(QtCore.QRect(200, 0, 201, 411))
        self.verticalGroupBox_3.setObjectName("verticalGroupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalGroupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lineEdit_PlaceOrder_OrderID = QtWidgets.QLineEdit(self.verticalGroupBox_3)
        self.lineEdit_PlaceOrder_OrderID.setText("")
        self.lineEdit_PlaceOrder_OrderID.setObjectName("lineEdit_PlaceOrder_OrderID")
        self.verticalLayout_3.addWidget(self.lineEdit_PlaceOrder_OrderID)
        self.lineEdit_PlaceOrder_CustomerID = QtWidgets.QLineEdit(self.verticalGroupBox_3)
        self.lineEdit_PlaceOrder_CustomerID.setObjectName("lineEdit_PlaceOrder_CustomerID")
        self.verticalLayout_3.addWidget(self.lineEdit_PlaceOrder_CustomerID)
        self.lineEdit_PlaceOrder_CustomerName = QtWidgets.QLineEdit(self.verticalGroupBox_3)
        self.lineEdit_PlaceOrder_CustomerName.setObjectName("lineEdit_PlaceOrder_CustomerName")
        self.verticalLayout_3.addWidget(self.lineEdit_PlaceOrder_CustomerName)
        self.lineEdit_PlaceOrder_CartID = QtWidgets.QLineEdit(self.verticalGroupBox_3)
        self.lineEdit_PlaceOrder_CartID.setText("")
        self.lineEdit_PlaceOrder_CartID.setObjectName("lineEdit_PlaceOrder_CartID")
        self.verticalLayout_3.addWidget(self.lineEdit_PlaceOrder_CartID)
        self.lineEdit_PlaceOrder_OrderPrce = QtWidgets.QLineEdit(self.verticalGroupBox_3)
        self.lineEdit_PlaceOrder_OrderPrce.setText("")
        self.lineEdit_PlaceOrder_OrderPrce.setObjectName("lineEdit_PlaceOrder_OrderPrce")
        self.verticalLayout_3.addWidget(self.lineEdit_PlaceOrder_OrderPrce)
        self.lineEdit_PlaceOrder_DateCreated = QtWidgets.QLineEdit(self.verticalGroupBox_3)
        self.lineEdit_PlaceOrder_DateCreated.setText("")
        self.lineEdit_PlaceOrder_DateCreated.setObjectName("lineEdit_PlaceOrder_DateCreated")
        self.verticalLayout_3.addWidget(self.lineEdit_PlaceOrder_DateCreated)
        self.lineEdit_PlaceOrder_DateShipped = QtWidgets.QLineEdit(self.verticalGroupBox_3)
        self.lineEdit_PlaceOrder_DateShipped.setText("")
        self.lineEdit_PlaceOrder_DateShipped.setObjectName("lineEdit_PlaceOrder_DateShipped")
        self.verticalLayout_3.addWidget(self.lineEdit_PlaceOrder_DateShipped)
        self.verticalGroupBox_4 = QtWidgets.QGroupBox(self.place_order_tab)
        self.verticalGroupBox_4.setGeometry(QtCore.QRect(0, 0, 201, 411))
        self.verticalGroupBox_4.setObjectName("verticalGroupBox_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalGroupBox_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_11 = QtWidgets.QLabel(self.verticalGroupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.verticalGroupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.label_16 = QtWidgets.QLabel(self.verticalGroupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_4.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.verticalGroupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_4.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.verticalGroupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_4.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.verticalGroupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_4.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.verticalGroupBox_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_4.addWidget(self.label_20)
        self.pushButton_Order_Confirm = QtWidgets.QPushButton(self.place_order_tab)
        self.pushButton_Order_Confirm.setGeometry(QtCore.QRect(500, 150, 171, 81))
        self.pushButton_Order_Confirm.setObjectName("pushButton_Order_Confirm")
        self.label_2 = QtWidgets.QLabel(self.place_order_tab)
        self.label_2.setGeometry(QtCore.QRect(430, 102, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Order_Tab.addTab(self.place_order_tab, "")
        self.update_order_tab = QtWidgets.QWidget()
        self.update_order_tab.setObjectName("update_order_tab")
        self.label_26 = QtWidgets.QLabel(self.update_order_tab)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_26.setFont(font)
        self.label_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.update_order_tab)
        self.label_27.setGeometry(QtCore.QRect(10, 180, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_27.setFont(font)
        self.label_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_27.setObjectName("label_27")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.update_order_tab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 230, 351, 80))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_4.addWidget(self.label_32)
        self.lineEdit_Order2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_Order2.setText("")
        self.lineEdit_Order2.setObjectName("lineEdit_Order2")
        self.horizontalLayout_4.addWidget(self.lineEdit_Order2)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.update_order_tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 60, 351, 80))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_33 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_5.addWidget(self.label_33)
        self.lineEdit_Order_input1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.lineEdit_Order_input1.setText("")
        self.lineEdit_Order_input1.setObjectName("lineEdit_Order_input1")
        self.horizontalLayout_5.addWidget(self.lineEdit_Order_input1)
        self.pushButton_Order_Update = QtWidgets.QPushButton(self.update_order_tab)
        self.pushButton_Order_Update.setGeometry(QtCore.QRect(460, 200, 171, 81))
        self.pushButton_Order_Update.setObjectName("pushButton_Order_Update")
        self.Order_Tab.addTab(self.update_order_tab, "")
        self.view_order_tab = QtWidgets.QWidget()
        self.view_order_tab.setObjectName("view_order_tab")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.view_order_tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 110, 861, 241))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(7)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        self.pushButton_Order_View = QtWidgets.QPushButton(self.view_order_tab)
        self.pushButton_Order_View.setGeometry(QtCore.QRect(350, 370, 171, 81))
        self.pushButton_Order_View.setObjectName("pushButton_Order_View")
        self.Order_Tab.addTab(self.view_order_tab, "")
        self.del_order_tab = QtWidgets.QWidget()
        self.del_order_tab.setObjectName("del_order_tab")
        self.label_42 = QtWidgets.QLabel(self.del_order_tab)
        self.label_42.setGeometry(QtCore.QRect(10, 20, 601, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_42.setFont(font)
        self.label_42.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_42.setObjectName("label_42")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.del_order_tab)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 80, 351, 80))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_43 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_10.addWidget(self.label_43)
        self.lineEdit_Order_Delete = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.lineEdit_Order_Delete.setText("")
        self.lineEdit_Order_Delete.setObjectName("lineEdit_Order_Delete")
        self.horizontalLayout_10.addWidget(self.lineEdit_Order_Delete)
        self.pushButton_Order_Delete = QtWidgets.QPushButton(self.del_order_tab)
        self.pushButton_Order_Delete.setGeometry(QtCore.QRect(390, 80, 171, 81))
        self.pushButton_Order_Delete.setObjectName("pushButton_Order_Delete")
        self.Order_Tab.addTab(self.del_order_tab, "")
        self.Main_Tab.addTab(self.order, "")
        self.shoppingCart = QtWidgets.QWidget()
        self.shoppingCart.setObjectName("shoppingCart")
        self.Shopping_Tab = QtWidgets.QTabWidget(self.shoppingCart)
        self.Shopping_Tab.setGeometry(QtCore.QRect(0, 10, 851, 471))
        self.Shopping_Tab.setObjectName("Shopping_Tab")
        self.add_item_tab = QtWidgets.QWidget()
        self.add_item_tab.setObjectName("add_item_tab")
        self.verticalGroupBox_5 = QtWidgets.QGroupBox(self.add_item_tab)
        self.verticalGroupBox_5.setGeometry(QtCore.QRect(160, 0, 160, 411))
        self.verticalGroupBox_5.setObjectName("verticalGroupBox_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalGroupBox_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_AddItem_CartID = QtWidgets.QLineEdit(self.verticalGroupBox_5)
        self.lineEdit_AddItem_CartID.setText("")
        self.lineEdit_AddItem_CartID.setObjectName("lineEdit_AddItem_CartID")
        self.verticalLayout_5.addWidget(self.lineEdit_AddItem_CartID)
        self.lineEdit_AddItem_CustomerID = QtWidgets.QLineEdit(self.verticalGroupBox_5)
        self.lineEdit_AddItem_CustomerID.setObjectName("lineEdit_AddItem_CustomerID")
        self.verticalLayout_5.addWidget(self.lineEdit_AddItem_CustomerID)
        self.lineEditAddItem_CookieID = QtWidgets.QLineEdit(self.verticalGroupBox_5)
        self.lineEditAddItem_CookieID.setObjectName("lineEditAddItem_CookieID")
        self.verticalLayout_5.addWidget(self.lineEditAddItem_CookieID)
        self.lineEdit_AddItem_Quantity = QtWidgets.QLineEdit(self.verticalGroupBox_5)
        self.lineEdit_AddItem_Quantity.setText("")
        self.lineEdit_AddItem_Quantity.setObjectName("lineEdit_AddItem_Quantity")
        self.verticalLayout_5.addWidget(self.lineEdit_AddItem_Quantity)
        self.lineEdit_AddItem_DateAdded = QtWidgets.QLineEdit(self.verticalGroupBox_5)
        self.lineEdit_AddItem_DateAdded.setText("")
        self.lineEdit_AddItem_DateAdded.setObjectName("lineEdit_AddItem_DateAdded")
        self.verticalLayout_5.addWidget(self.lineEdit_AddItem_DateAdded)
        self.verticalGroupBox_6 = QtWidgets.QGroupBox(self.add_item_tab)
        self.verticalGroupBox_6.setGeometry(QtCore.QRect(0, 0, 160, 411))
        self.verticalGroupBox_6.setObjectName("verticalGroupBox_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalGroupBox_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_21 = QtWidgets.QLabel(self.verticalGroupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_6.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.verticalGroupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_6.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.verticalGroupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_6.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.verticalGroupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_6.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.verticalGroupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_6.addWidget(self.label_25)
        self.pushButton_AddItem_Confirm = QtWidgets.QPushButton(self.add_item_tab)
        self.pushButton_AddItem_Confirm.setGeometry(QtCore.QRect(450, 140, 171, 81))
        self.pushButton_AddItem_Confirm.setObjectName("pushButton_AddItem_Confirm")
        self.label_4 = QtWidgets.QLabel(self.add_item_tab)
        self.label_4.setGeometry(QtCore.QRect(370, 80, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Shopping_Tab.addTab(self.add_item_tab, "")
        self.update_item_tab = QtWidgets.QWidget()
        self.update_item_tab.setObjectName("update_item_tab")
        self.label_34 = QtWidgets.QLabel(self.update_item_tab)
        self.label_34.setGeometry(QtCore.QRect(0, 0, 571, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_34.setFont(font)
        self.label_34.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.update_item_tab)
        self.label_35.setGeometry(QtCore.QRect(0, 170, 631, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_35.setFont(font)
        self.label_35.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_35.setObjectName("label_35")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.update_item_tab)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 220, 351, 80))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_36 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.horizontalLayout_6.addWidget(self.label_36)
        self.lineEdit_ShoppingCart_Update_Quantity_Input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.lineEdit_ShoppingCart_Update_Quantity_Input.setText("")
        self.lineEdit_ShoppingCart_Update_Quantity_Input.setObjectName("lineEdit_ShoppingCart_Update_Quantity_Input")
        self.horizontalLayout_6.addWidget(self.lineEdit_ShoppingCart_Update_Quantity_Input)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.update_item_tab)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 50, 351, 80))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_37 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.horizontalLayout_7.addWidget(self.label_37)
        self.lineEdit_ShoppingCart_Update_CartID_Input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.lineEdit_ShoppingCart_Update_CartID_Input.setText("")
        self.lineEdit_ShoppingCart_Update_CartID_Input.setObjectName("lineEdit_ShoppingCart_Update_CartID_Input")
        self.horizontalLayout_7.addWidget(self.lineEdit_ShoppingCart_Update_CartID_Input)
        self.pushButton_Update_Update = QtWidgets.QPushButton(self.update_item_tab)
        self.pushButton_Update_Update.setGeometry(QtCore.QRect(410, 220, 171, 81))
        self.pushButton_Update_Update.setObjectName("pushButton_Update_Update")
        self.Shopping_Tab.addTab(self.update_item_tab, "")
        self.view_cart_tab = QtWidgets.QWidget()
        self.view_cart_tab.setObjectName("view_cart_tab")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.view_cart_tab)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 80, 781, 241))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(5)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        self.pushButton_CartDetails_View = QtWidgets.QPushButton(self.view_cart_tab)
        self.pushButton_CartDetails_View.setGeometry(QtCore.QRect(330, 340, 171, 81))
        self.pushButton_CartDetails_View.setObjectName("pushButton_CartDetails_View")
        self.Shopping_Tab.addTab(self.view_cart_tab, "")
        self.check_out_tab = QtWidgets.QWidget()
        self.check_out_tab.setObjectName("check_out_tab")
        self.pushButton_ShoppingCart_Checkout = QtWidgets.QPushButton(self.check_out_tab)
        self.pushButton_ShoppingCart_Checkout.setGeometry(QtCore.QRect(330, 170, 171, 81))
        self.pushButton_ShoppingCart_Checkout.setObjectName("pushButton_ShoppingCart_Checkout")
        self.label_6 = QtWidgets.QLabel(self.check_out_tab)
        self.label_6.setGeometry(QtCore.QRect(250, 100, 331, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.Shopping_Tab.addTab(self.check_out_tab, "")
        self.Main_Tab.addTab(self.shoppingCart, "")
        self.cookies = QtWidgets.QWidget()
        self.cookies.setObjectName("cookies")
        self.Cookies_Tab = QtWidgets.QTabWidget(self.cookies)
        self.Cookies_Tab.setGeometry(QtCore.QRect(10, 0, 731, 491))
        self.Cookies_Tab.setObjectName("Cookies_Tab")
        self.add_product_tab = QtWidgets.QWidget()
        self.add_product_tab.setObjectName("add_product_tab")
        self.verticalGroupBox_7 = QtWidgets.QGroupBox(self.add_product_tab)
        self.verticalGroupBox_7.setGeometry(QtCore.QRect(160, 10, 160, 411))
        self.verticalGroupBox_7.setObjectName("verticalGroupBox_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalGroupBox_7)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit_AddProduct_CookieID = QtWidgets.QLineEdit(self.verticalGroupBox_7)
        self.lineEdit_AddProduct_CookieID.setText("")
        self.lineEdit_AddProduct_CookieID.setObjectName("lineEdit_AddProduct_CookieID")
        self.verticalLayout_7.addWidget(self.lineEdit_AddProduct_CookieID)
        self.lineEdit_AddProduct_CookieName = QtWidgets.QLineEdit(self.verticalGroupBox_7)
        self.lineEdit_AddProduct_CookieName.setObjectName("lineEdit_AddProduct_CookieName")
        self.verticalLayout_7.addWidget(self.lineEdit_AddProduct_CookieName)
        self.lineEdit_AddProduct_UnitCost = QtWidgets.QLineEdit(self.verticalGroupBox_7)
        self.lineEdit_AddProduct_UnitCost.setObjectName("lineEdit_AddProduct_UnitCost")
        self.verticalLayout_7.addWidget(self.lineEdit_AddProduct_UnitCost)
        self.lineEdit_AddProduct_SoldOut = QtWidgets.QLineEdit(self.verticalGroupBox_7)
        self.lineEdit_AddProduct_SoldOut.setText("")
        self.lineEdit_AddProduct_SoldOut.setObjectName("lineEdit_AddProduct_SoldOut")
        self.verticalLayout_7.addWidget(self.lineEdit_AddProduct_SoldOut)
        self.verticalGroupBox_8 = QtWidgets.QGroupBox(self.add_product_tab)
        self.verticalGroupBox_8.setGeometry(QtCore.QRect(0, 10, 160, 411))
        self.verticalGroupBox_8.setObjectName("verticalGroupBox_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalGroupBox_8)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_28 = QtWidgets.QLabel(self.verticalGroupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_8.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.verticalGroupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_8.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.verticalGroupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_8.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.verticalGroupBox_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_8.addWidget(self.label_31)
        self.pushButton_Cookies_AddProduct_Confirm = QtWidgets.QPushButton(self.add_product_tab)
        self.pushButton_Cookies_AddProduct_Confirm.setGeometry(QtCore.QRect(420, 170, 171, 81))
        self.pushButton_Cookies_AddProduct_Confirm.setObjectName("pushButton_Cookies_AddProduct_Confirm")
        self.label_5 = QtWidgets.QLabel(self.add_product_tab)
        self.label_5.setGeometry(QtCore.QRect(360, 110, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Cookies_Tab.addTab(self.add_product_tab, "")
        self.Update_product_tab = QtWidgets.QWidget()
        self.Update_product_tab.setObjectName("Update_product_tab")
        self.label_38 = QtWidgets.QLabel(self.Update_product_tab)
        self.label_38.setGeometry(QtCore.QRect(30, 0, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_38.setFont(font)
        self.label_38.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.Update_product_tab)
        self.label_39.setGeometry(QtCore.QRect(30, 170, 501, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_39.setFont(font)
        self.label_39.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_39.setObjectName("label_39")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.Update_product_tab)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(30, 220, 351, 80))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_40 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.horizontalLayout_8.addWidget(self.label_40)
        self.lineEdit_Cookies_UnitCost_Input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_8)
        self.lineEdit_Cookies_UnitCost_Input.setText("")
        self.lineEdit_Cookies_UnitCost_Input.setObjectName("lineEdit_Cookies_UnitCost_Input")
        self.horizontalLayout_8.addWidget(self.lineEdit_Cookies_UnitCost_Input)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.Update_product_tab)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(30, 50, 351, 80))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_41 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.horizontalLayout_9.addWidget(self.label_41)
        self.lineEdit_Cookies_CookieID_Input = QtWidgets.QLineEdit(self.horizontalLayoutWidget_9)
        self.lineEdit_Cookies_CookieID_Input.setText("")
        self.lineEdit_Cookies_CookieID_Input.setObjectName("lineEdit_Cookies_CookieID_Input")
        self.horizontalLayout_9.addWidget(self.lineEdit_Cookies_CookieID_Input)
        self.pushButton_Cookies_Update = QtWidgets.QPushButton(self.Update_product_tab)
        self.pushButton_Cookies_Update.setGeometry(QtCore.QRect(110, 340, 171, 81))
        self.pushButton_Cookies_Update.setObjectName("pushButton_Cookies_Update")
        self.Cookies_Tab.addTab(self.Update_product_tab, "")
        self.view_product_tab = QtWidgets.QWidget()
        self.view_product_tab.setObjectName("view_product_tab")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.view_product_tab)
        self.tableWidget_4.setGeometry(QtCore.QRect(80, 80, 571, 241))
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        self.pushButton_Cookies_View = QtWidgets.QPushButton(self.view_product_tab)
        self.pushButton_Cookies_View.setGeometry(QtCore.QRect(290, 340, 171, 81))
        self.pushButton_Cookies_View.setObjectName("pushButton_Cookies_View")
        self.Cookies_Tab.addTab(self.view_product_tab, "")
        self.del_product_tab = QtWidgets.QWidget()
        self.del_product_tab.setObjectName("del_product_tab")
        self.label_46 = QtWidgets.QLabel(self.del_product_tab)
        self.label_46.setGeometry(QtCore.QRect(10, 10, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_46.setFont(font)
        self.label_46.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_46.setObjectName("label_46")
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.del_product_tab)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(60, 50, 351, 80))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_47 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_12.addWidget(self.label_47)
        self.lineEdit_Cookies_CookieID_Delete = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        self.lineEdit_Cookies_CookieID_Delete.setText("")
        self.lineEdit_Cookies_CookieID_Delete.setObjectName("lineEdit_Cookies_CookieID_Delete")
        self.horizontalLayout_12.addWidget(self.lineEdit_Cookies_CookieID_Delete)
        self.pushButton_Cookies_CookieID_Delete = QtWidgets.QPushButton(self.del_product_tab)
        self.pushButton_Cookies_CookieID_Delete.setGeometry(QtCore.QRect(150, 140, 171, 81))
        self.pushButton_Cookies_CookieID_Delete.setObjectName("pushButton_Cookies_CookieID_Delete")
        self.Cookies_Tab.addTab(self.del_product_tab, "")
        self.Main_Tab.addTab(self.cookies, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Main_Tab.setCurrentIndex(0)
        self.Customer_Tab.setCurrentIndex(0)
        self.Order_Tab.setCurrentIndex(1)
        self.Shopping_Tab.setCurrentIndex(3)
        self.Cookies_Tab.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "09892205Assignment3"))
        self.pushButton_3.setText(_translate("MainWindow", "Create Database"))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.Initialize_Tab), _translate("MainWindow", "Create DB"))
        self.label_CustomerID.setText(_translate("MainWindow", "Customer ID"))
        self.label_FirstName.setText(_translate("MainWindow", "First Name"))
        self.label_LastName.setText(_translate("MainWindow", "Last Name"))
        self.label_Address.setText(_translate("MainWindow", "Address"))
        self.label_Email.setText(_translate("MainWindow", "Email"))
        self.label_Phone.setText(_translate("MainWindow", "Phone"))
        self.label_CreditCard.setText(_translate("MainWindow", "Credit Card"))
        self.pushButton_CreateCustomer_Confirm.setText(_translate("MainWindow", "Confirm"))
        self.label_3.setText(_translate("MainWindow", "Please Enter Data into all boxes for this to work properly."))
        self.Customer_Tab.setTabText(self.Customer_Tab.indexOf(self.create_cus_tab), _translate("MainWindow", "Create Customer"))
        item = self.tableWidget_CustomerDetail.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "CustomerID"))
        item = self.tableWidget_CustomerDetail.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "First Name"))
        item = self.tableWidget_CustomerDetail.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Last Name"))
        item = self.tableWidget_CustomerDetail.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Address"))
        item = self.tableWidget_CustomerDetail.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget_CustomerDetail.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Phone"))
        item = self.tableWidget_CustomerDetail.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Credit Card"))
        self.pushButton_CustomerDetail_View.setText(_translate("MainWindow", "View"))
        self.Customer_Tab.setTabText(self.Customer_Tab.indexOf(self.view_cus_tab), _translate("MainWindow", "Customer Details"))
        self.label_UpdateText2.setText(_translate("MainWindow", "Enter the new Last Name You want to change below:"))
        self.label_LastName_2.setText(_translate("MainWindow", "Last Name"))
        self.label_UpdateText1.setText(_translate("MainWindow", "Enter The customer\'s ID you want to update below:"))
        self.label_FirstName_2.setText(_translate("MainWindow", "Customer ID"))
        self.pushButton_UpdateCustomer_Update.setText(_translate("MainWindow", "Update"))
        self.Customer_Tab.setTabText(self.Customer_Tab.indexOf(self.update_cus_tab), _translate("MainWindow", "Update Custoner"))
        self.label_DelereCustomer.setText(_translate("MainWindow", "Customer ID"))
        self.pushButton_DelereCustomer_Delete.setText(_translate("MainWindow", "Delete"))
        self.label_DelereCustomer_2.setText(_translate("MainWindow", "Enter The customer\'s ID you want to delete below:"))
        self.Customer_Tab.setTabText(self.Customer_Tab.indexOf(self.del_cus_tab), _translate("MainWindow", "Delete Customer"))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.customer), _translate("MainWindow", "Customer"))
        self.label_11.setText(_translate("MainWindow", "Order ID"))
        self.label_12.setText(_translate("MainWindow", "Customer ID"))
        self.label_16.setText(_translate("MainWindow", "Customer Name"))
        self.label_17.setText(_translate("MainWindow", "Cart ID"))
        self.label_18.setText(_translate("MainWindow", "Order Price"))
        self.label_19.setText(_translate("MainWindow", "Date Created"))
        self.label_20.setText(_translate("MainWindow", "Date Shipped"))
        self.pushButton_Order_Confirm.setText(_translate("MainWindow", "Confirm"))
        self.label_2.setText(_translate("MainWindow", "Please Enter Data into all boxes for this to work properly."))
        self.Order_Tab.setTabText(self.Order_Tab.indexOf(self.place_order_tab), _translate("MainWindow", "Place Order"))
        self.label_26.setText(_translate("MainWindow", "Enter The Order\'s ID you want to update below:"))
        self.label_27.setText(_translate("MainWindow", "Enter the new Price:"))
        self.label_32.setText(_translate("MainWindow", "Price"))
        self.label_33.setText(_translate("MainWindow", "Order\'s ID"))
        self.pushButton_Order_Update.setText(_translate("MainWindow", "Update"))
        self.Order_Tab.setTabText(self.Order_Tab.indexOf(self.update_order_tab), _translate("MainWindow", "Update Order"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "OrderID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "CustomerID"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Customer Name"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CartID"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Order Price"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Date Created"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Date Shipped"))
        self.pushButton_Order_View.setText(_translate("MainWindow", "View"))
        self.Order_Tab.setTabText(self.Order_Tab.indexOf(self.view_order_tab), _translate("MainWindow", "View Order"))
        self.label_42.setText(_translate("MainWindow", "Enter The Order\'s ID you want to delete below:"))
        self.label_43.setText(_translate("MainWindow", "Orders ID"))
        self.pushButton_Order_Delete.setText(_translate("MainWindow", "Delete"))
        self.Order_Tab.setTabText(self.Order_Tab.indexOf(self.del_order_tab), _translate("MainWindow", "Delete Order"))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.order), _translate("MainWindow", "Order"))
        self.label_21.setText(_translate("MainWindow", "Cart ID"))
        self.label_22.setText(_translate("MainWindow", "Customer ID"))
        self.label_23.setText(_translate("MainWindow", "Cookie ID"))
        self.label_24.setText(_translate("MainWindow", "Quantity"))
        self.label_25.setText(_translate("MainWindow", "Date Added"))
        self.pushButton_AddItem_Confirm.setText(_translate("MainWindow", "Confirm"))
        self.label_4.setText(_translate("MainWindow", "Please Enter Data into all boxes for this to work properly."))
        self.Shopping_Tab.setTabText(self.Shopping_Tab.indexOf(self.add_item_tab), _translate("MainWindow", "Add Item"))
        self.label_34.setText(_translate("MainWindow", "Enter The Cart\'s ID you want to update below:"))
        self.label_35.setText(_translate("MainWindow", "Enter the new Quantity You want to change below:"))
        self.label_36.setText(_translate("MainWindow", "Amount"))
        self.label_37.setText(_translate("MainWindow", "Cart\'s ID"))
        self.pushButton_Update_Update.setText(_translate("MainWindow", "Update"))
        self.Shopping_Tab.setTabText(self.Shopping_Tab.indexOf(self.update_item_tab), _translate("MainWindow", "Update Cart"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cart ID"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Customer ID"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Cookie ID"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "quantity"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date Added"))
        self.pushButton_CartDetails_View.setText(_translate("MainWindow", "View"))
        self.Shopping_Tab.setTabText(self.Shopping_Tab.indexOf(self.view_cart_tab), _translate("MainWindow", "Cart Details"))
        self.pushButton_ShoppingCart_Checkout.setText(_translate("MainWindow", "CheckOut"))
        self.label_6.setText(_translate("MainWindow", "Click CheckOut to Complete Order"))
        self.Shopping_Tab.setTabText(self.Shopping_Tab.indexOf(self.check_out_tab), _translate("MainWindow", "Check Out"))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.shoppingCart), _translate("MainWindow", "Shopping Cart"))
        self.label_28.setText(_translate("MainWindow", "CookieID"))
        self.label_29.setText(_translate("MainWindow", "Cookie Name"))
        self.label_30.setText(_translate("MainWindow", "Unit Cost"))
        self.label_31.setText(_translate("MainWindow", "Sold Out?"))
        self.pushButton_Cookies_AddProduct_Confirm.setText(_translate("MainWindow", "Confirm"))
        self.label_5.setText(_translate("MainWindow", "Please Enter Data into all boxes for this to work properly."))
        self.Cookies_Tab.setTabText(self.Cookies_Tab.indexOf(self.add_product_tab), _translate("MainWindow", "Add Product"))
        self.label_38.setText(_translate("MainWindow", "Enter The Cookie\'s ID you want to update below:"))
        self.label_39.setText(_translate("MainWindow", "Enter the new Unit Cost:"))
        self.label_40.setText(_translate("MainWindow", "New Cost"))
        self.label_41.setText(_translate("MainWindow", "Cookie ID"))
        self.pushButton_Cookies_Update.setText(_translate("MainWindow", "Update"))
        self.Cookies_Tab.setTabText(self.Cookies_Tab.indexOf(self.Update_product_tab), _translate("MainWindow", "Update Product"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Cookie ID"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Cookie Name"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Unit Cost"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "SoldOut"))
        self.pushButton_Cookies_View.setText(_translate("MainWindow", "View"))
        self.Cookies_Tab.setTabText(self.Cookies_Tab.indexOf(self.view_product_tab), _translate("MainWindow", "Product Details"))
        self.label_46.setText(_translate("MainWindow", "Enter The Cookies ID you want to delete below:"))
        self.label_47.setText(_translate("MainWindow", "Cookie ID"))
        self.pushButton_Cookies_CookieID_Delete.setText(_translate("MainWindow", "Delete"))
        self.Cookies_Tab.setTabText(self.Cookies_Tab.indexOf(self.del_product_tab), _translate("MainWindow", "Delete Product"))
        self.Main_Tab.setTabText(self.Main_Tab.indexOf(self.cookies), _translate("MainWindow", "Cookies"))